apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
  name: vote-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: vote-api
